services:
  db:
    image: postgres:15-alpine
    container_name: foodstreet_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: food_street_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: foodstreet_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/food_street_db
      - WEB_DIR=/web
    depends_on:
      - db
    volumes:
      - .:/app
      - ../Web:/web:ro

volumes:
  postgres_data:
