namespace FoodStreetAudioGuide
{
    public static class AppText
    {
        public const string Vietnamese = "Tiếng Việt";
        public const string English = "English";
        public const string Chinese = "中文 (Chinese)";
        public const string Japanese = "日本語 (Japanese)";
        public const string Korean = "한국어 (Korean)";

        private static readonly IReadOnlyDictionary<string, LocalizedText> TextByLanguage =
            new Dictionary<string, LocalizedText>
            {
                [Vietnamese] = new()
                {
                    PageTitle = "Danh sách quầy",
                    SearchHint = "Tìm quầy ăn, món ăn...",
                    NearbyFilter = "Gần đây",
                    OpenNowFilter = "Đang mở",
                    TopRatedFilter = "Đánh giá cao",
                    Under200Filter = "Dưới 200m",
                    ExploreTab = "KHÁM PHÁ",
                    MapTab = "BẢN ĐỒ",
                    SavedTab = "ĐÃ LƯU",
                    AwayLabel = "KHOẢNG CÁCH",
                    UnavailableContentMessage = "Nội dung chưa sẵn sàng. Đổi ngôn ngữ?",
                    CancelText = "Hủy",
                    ErrorTitle = "Lỗi",
                    AudioErrorPrefix = "Không thể phát âm thanh: ",
                    ScriptDialogTitle = "Giới thiệu gian hàng",
                    CloseText = "Đóng",
                    PopupCuisineLabel = "Quầy bán",
                    PopupDistanceLabel = "Khoảng cách",
                    PopupRatingLabel = "Đánh giá",
                    PopupReviewsLabel = "Lượt review",
                    PopupHoursLabel = "Giờ hoạt động",
                    PopupSpecialtiesLabel = "3 món đặc sản",
                    AudioReadyLabel = "Audio offline đã tải",
                    AudioNotReadyLabel = "Chưa tải audio offline",
                    DownloadAudioButton = "Tải trước audio",
                    DownloadingAudioButton = "Đang tải audio...",
                    AudioDownloadedMessage = "Đã tải audio để nghe offline.",
                    AudioDownloadFailedMessage = "Chưa tải được audio lúc này.",
                    DownloadedAudioTitle = "Audio đã tải",
                    DownloadedAudioEmpty = "Chưa có audio offline nào được tải.",
                    DeleteText = "Xóa",
                    LanguageLabel = "Ngôn ngữ",
                    DownloadedAtLabel = "Tải lúc",
                    LanguageSelectionTitle = "Chọn ngôn ngữ của bạn",
                    RecommendedLabel = "Đề xuất",
                    ContinueButton = "Tiếp tục",
                    ChangeAnytimeText = "Bạn có thể thay đổi bất cứ lúc nào"
                },
                [English] = new()
                {
                    PageTitle = "Stall List",
                    SearchHint = "Search food stalls, cuisines...",
                    NearbyFilter = "Nearby",
                    OpenNowFilter = "Open Now",
                    TopRatedFilter = "Top Rated",
                    Under200Filter = "Under 200m",
                    ExploreTab = "EXPLORES",
                    MapTab = "MAP",
                    SavedTab = "SAVED",
                    AwayLabel = "AWAY",
                    UnavailableContentMessage = "Content is not ready yet. Change language?",
                    CancelText = "Cancel",
                    ErrorTitle = "Error",
                    AudioErrorPrefix = "Unable to play audio: ",
                    ScriptDialogTitle = "Stall Introduction",
                    CloseText = "Close",
                    PopupCuisineLabel = "Serves",
                    PopupDistanceLabel = "Distance",
                    PopupRatingLabel = "Rating",
                    PopupReviewsLabel = "Reviews",
                    PopupHoursLabel = "Hours",
                    PopupSpecialtiesLabel = "3 signature dishes",
                    AudioReadyLabel = "Offline audio ready",
                    AudioNotReadyLabel = "Offline audio not downloaded",
                    DownloadAudioButton = "Download audio",
                    DownloadingAudioButton = "Downloading audio...",
                    AudioDownloadedMessage = "Audio is ready for offline playback.",
                    AudioDownloadFailedMessage = "Unable to download audio right now.",
                    DownloadedAudioTitle = "Downloaded Audio",
                    DownloadedAudioEmpty = "No offline audio has been downloaded yet.",
                    DeleteText = "Delete",
                    LanguageLabel = "Language",
                    DownloadedAtLabel = "Downloaded",
                    LanguageSelectionTitle = "Select Your Language",
                    RecommendedLabel = "Recommended",
                    ContinueButton = "Continue",
                    ChangeAnytimeText = "You can change this anytime"
                },
                [Chinese] = new()
                {
                    PageTitle = "摊位列表",
                    SearchHint = "搜索美食摊位...",
                    NearbyFilter = "附近",
                    OpenNowFilter = "营业中",
                    TopRatedFilter = "高评分",
                    Under200Filter = "200米内",
                    ExploreTab = "探索",
                    MapTab = "地图",
                    SavedTab = "收藏",
                    AwayLabel = "距离",
                    UnavailableContentMessage = "内容尚未准备好。要切换语言吗？",
                    CancelText = "取消",
                    ErrorTitle = "错误",
                    AudioErrorPrefix = "无法播放音频：",
                    ScriptDialogTitle = "摊位介绍",
                    CloseText = "关闭",
                    PopupCuisineLabel = "售卖",
                    PopupDistanceLabel = "距离",
                    PopupRatingLabel = "评分",
                    PopupReviewsLabel = "评论数",
                    PopupHoursLabel = "营业时间",
                    PopupSpecialtiesLabel = "3 道招牌菜",
                    AudioReadyLabel = "离线音频已下载",
                    AudioNotReadyLabel = "尚未下载离线音频",
                    DownloadAudioButton = "下载音频",
                    DownloadingAudioButton = "正在下载音频...",
                    AudioDownloadedMessage = "音频已可离线播放。",
                    AudioDownloadFailedMessage = "暂时无法下载音频。",
                    DownloadedAudioTitle = "已下载音频",
                    DownloadedAudioEmpty = "还没有下载任何离线音频。",
                    DeleteText = "删除",
                    LanguageLabel = "语言",
                    DownloadedAtLabel = "下载时间",
                    LanguageSelectionTitle = "选择您的语言",
                    RecommendedLabel = "推荐",
                    ContinueButton = "继续",
                    ChangeAnytimeText = "您可以随时更改"
                },
                [Japanese] = new()
                {
                    PageTitle = "屋台一覧",
                    SearchHint = "屋台や料理を検索...",
                    NearbyFilter = "近く",
                    OpenNowFilter = "営業中",
                    TopRatedFilter = "高評価",
                    Under200Filter = "200m以内",
                    ExploreTab = "探索",
                    MapTab = "地図",
                    SavedTab = "保存済み",
                    AwayLabel = "距離",
                    UnavailableContentMessage = "コンテンツの準備ができていません。言語を変更しますか？",
                    CancelText = "キャンセル",
                    ErrorTitle = "エラー",
                    AudioErrorPrefix = "音声を再生できません: ",
                    ScriptDialogTitle = "屋台紹介",
                    CloseText = "閉じる",
                    PopupCuisineLabel = "販売内容",
                    PopupDistanceLabel = "距離",
                    PopupRatingLabel = "評価",
                    PopupReviewsLabel = "レビュー数",
                    PopupHoursLabel = "営業時間",
                    PopupSpecialtiesLabel = "おすすめ3品",
                    AudioReadyLabel = "オフライン音声を保存済み",
                    AudioNotReadyLabel = "オフライン音声は未保存",
                    DownloadAudioButton = "音声を保存",
                    DownloadingAudioButton = "音声を保存中...",
                    AudioDownloadedMessage = "オフライン再生用の音声を保存しました。",
                    AudioDownloadFailedMessage = "今は音声を保存できません。",
                    DownloadedAudioTitle = "保存済み音声",
                    DownloadedAudioEmpty = "まだオフライン音声は保存されていません。",
                    DeleteText = "削除",
                    LanguageLabel = "言語",
                    DownloadedAtLabel = "保存日時",
                    LanguageSelectionTitle = "言語を選択",
                    RecommendedLabel = "おすすめ",
                    ContinueButton = "続行",
                    ChangeAnytimeText = "この設定はいつでも変更できます"
                },
                [Korean] = new()
                {
                    PageTitle = "가판대 목록",
                    SearchHint = "음식 가판대, 요리를 검색...",
                    NearbyFilter = "근처",
                    OpenNowFilter = "영업 중",
                    TopRatedFilter = "평점 높음",
                    Under200Filter = "200m 이내",
                    ExploreTab = "탐색",
                    MapTab = "지도",
                    SavedTab = "저장됨",
                    AwayLabel = "거리",
                    UnavailableContentMessage = "콘텐츠가 아직 준비되지 않았습니다. 언어를 변경할까요?",
                    CancelText = "취소",
                    ErrorTitle = "오류",
                    AudioErrorPrefix = "오디오를 재생할 수 없습니다: ",
                    ScriptDialogTitle = "가판대 소개",
                    CloseText = "닫기",
                    PopupCuisineLabel = "판매 메뉴",
                    PopupDistanceLabel = "거리",
                    PopupRatingLabel = "평점",
                    PopupReviewsLabel = "리뷰 수",
                    PopupHoursLabel = "운영 시간",
                    PopupSpecialtiesLabel = "대표 메뉴 3가지",
                    AudioReadyLabel = "오프라인 오디오 저장됨",
                    AudioNotReadyLabel = "오프라인 오디오 미저장",
                    DownloadAudioButton = "오디오 다운로드",
                    DownloadingAudioButton = "오디오 다운로드 중...",
                    AudioDownloadedMessage = "오프라인 재생용 오디오를 저장했습니다.",
                    AudioDownloadFailedMessage = "지금은 오디오를 다운로드할 수 없습니다.",
                    DownloadedAudioTitle = "저장된 오디오",
                    DownloadedAudioEmpty = "아직 다운로드한 오프라인 오디오가 없습니다.",
                    DeleteText = "삭제",
                    LanguageLabel = "언어",
                    DownloadedAtLabel = "다운로드 시각",
                    LanguageSelectionTitle = "언어 선택",
                    RecommendedLabel = "추천",
                    ContinueButton = "계속",
                    ChangeAnytimeText = "이 설정은 언제든지 변경할 수 있습니다"
                }
            };

        public static LocalizedText Get(string? language)
        {
            if (!string.IsNullOrWhiteSpace(language) && TextByLanguage.TryGetValue(language, out var text))
            {
                return text;
            }

            return TextByLanguage[English];
        }
    }
}
